# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import hephaestus_pb2 as hephaestus__pb2


class PythonAlgoServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.skuGroup = channel.unary_unary(
            '/PythonAlgoService/skuGroup',
            request_serializer=hephaestus__pb2.SkuGroupContext.SerializeToString,
            response_deserializer=hephaestus__pb2.SkuGroupResult.FromString,
        )
        self.skuRelation = channel.unary_unary(
            '/PythonAlgoService/skuRelation',
            request_serializer=hephaestus__pb2.SkuRelationContext.SerializeToString,
            response_deserializer=hephaestus__pb2.SkuRelationResult.FromString,
        )
        self.skuSalesPredict = channel.unary_unary(
            '/PythonAlgoService/skuSalesPredict',
            request_serializer=hephaestus__pb2.SkuSalePredictionContext.SerializeToString,
            response_deserializer=hephaestus__pb2.SkuSalePredictionResult.FromString,
        )


class PythonAlgoServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def skuGroup(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def skuRelation(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def skuSalesPredict(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PythonAlgoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'skuGroup': grpc.unary_unary_rpc_method_handler(
            servicer.skuGroup,
            request_deserializer=hephaestus__pb2.SkuGroupContext.FromString,
            response_serializer=hephaestus__pb2.SkuGroupResult.SerializeToString,
        ),
        'skuRelation': grpc.unary_unary_rpc_method_handler(
            servicer.skuRelation,
            request_deserializer=hephaestus__pb2.SkuRelationContext.FromString,
            response_serializer=hephaestus__pb2.SkuRelationResult.SerializeToString,
        ),
        'skuSalesPredict': grpc.unary_unary_rpc_method_handler(
            servicer.skuSalesPredict,
            request_deserializer=hephaestus__pb2.SkuSalePredictionContext.FromString,
            response_serializer=hephaestus__pb2.SkuSalePredictionResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'PythonAlgoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


class JavaAlgoServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.orderAllocation = channel.unary_unary(
            '/JavaAlgoService/orderAllocation',
            request_serializer=hephaestus__pb2.OrderAllocationContext.SerializeToString,
            response_deserializer=hephaestus__pb2.OrderAllocationResult.FromString,
        )
        self.orderGroup = channel.unary_unary(
            '/JavaAlgoService/orderGroup',
            request_serializer=hephaestus__pb2.OrderGroupContext.SerializeToString,
            response_deserializer=hephaestus__pb2.OrderGroupResult.FromString,
        )
        self.inventoryHit = channel.unary_unary(
            '/JavaAlgoService/inventoryHit',
            request_serializer=hephaestus__pb2.InventoryHitContext.SerializeToString,
            response_deserializer=hephaestus__pb2.InventoryHitResult.FromString,
        )
        self.repRecommend = channel.unary_unary(
            '/JavaAlgoService/repRecommend',
            request_serializer=hephaestus__pb2.RepRecommendContext.SerializeToString,
            response_deserializer=hephaestus__pb2.RepRecommendResult.FromString,
        )
        self.skuRelation = channel.unary_unary(
            '/JavaAlgoService/skuRelation',
            request_serializer=hephaestus__pb2.SkuRelationContext.SerializeToString,
            response_deserializer=hephaestus__pb2.SkuRelationResult.FromString,
        )


class JavaAlgoServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def orderAllocation(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def orderGroup(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def inventoryHit(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def repRecommend(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def skuRelation(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JavaAlgoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'orderAllocation': grpc.unary_unary_rpc_method_handler(
            servicer.orderAllocation,
            request_deserializer=hephaestus__pb2.OrderAllocationContext.FromString,
            response_serializer=hephaestus__pb2.OrderAllocationResult.SerializeToString,
        ),
        'orderGroup': grpc.unary_unary_rpc_method_handler(
            servicer.orderGroup,
            request_deserializer=hephaestus__pb2.OrderGroupContext.FromString,
            response_serializer=hephaestus__pb2.OrderGroupResult.SerializeToString,
        ),
        'inventoryHit': grpc.unary_unary_rpc_method_handler(
            servicer.inventoryHit,
            request_deserializer=hephaestus__pb2.InventoryHitContext.FromString,
            response_serializer=hephaestus__pb2.InventoryHitResult.SerializeToString,
        ),
        'repRecommend': grpc.unary_unary_rpc_method_handler(
            servicer.repRecommend,
            request_deserializer=hephaestus__pb2.RepRecommendContext.FromString,
            response_serializer=hephaestus__pb2.RepRecommendResult.SerializeToString,
        ),
        'skuRelation': grpc.unary_unary_rpc_method_handler(
            servicer.skuRelation,
            request_deserializer=hephaestus__pb2.SkuRelationContext.FromString,
            response_serializer=hephaestus__pb2.SkuRelationResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'JavaAlgoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


class PickSimulatorServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.run = channel.unary_unary(
            '/PickSimulatorService/run',
            request_serializer=hephaestus__pb2.PickSimulationContext.SerializeToString,
            response_deserializer=hephaestus__pb2.PickSimulationResult.FromString,
        )


class PickSimulatorServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def run(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PickSimulatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'run': grpc.unary_unary_rpc_method_handler(
            servicer.run,
            request_deserializer=hephaestus__pb2.PickSimulationContext.FromString,
            response_serializer=hephaestus__pb2.PickSimulationResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'PickSimulatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


class RobotSimulationServiceStub(object):
    """机器人模拟服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.createEnvironment = channel.unary_unary(
            '/RobotSimulationService/createEnvironment',
            request_serializer=hephaestus__pb2.EnvironmentCreateContext.SerializeToString,
            response_deserializer=hephaestus__pb2.EnvironmentCreateResult.FromString,
        )
        self.nextStep = channel.unary_unary(
            '/RobotSimulationService/nextStep',
            request_serializer=hephaestus__pb2.EnvironmentUpdateContext.SerializeToString,
            response_deserializer=hephaestus__pb2.EnvironmentDetail.FromString,
        )
        self.closeEnvironment = channel.unary_unary(
            '/RobotSimulationService/closeEnvironment',
            request_serializer=hephaestus__pb2.EnvironmentQuery.SerializeToString,
            response_deserializer=hephaestus__pb2.EnvironmentDetail.FromString,
        )


class RobotSimulationServiceServicer(object):
    """机器人模拟服务
    """

    def createEnvironment(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def nextStep(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def closeEnvironment(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotSimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'createEnvironment': grpc.unary_unary_rpc_method_handler(
            servicer.createEnvironment,
            request_deserializer=hephaestus__pb2.EnvironmentCreateContext.FromString,
            response_serializer=hephaestus__pb2.EnvironmentCreateResult.SerializeToString,
        ),
        'nextStep': grpc.unary_unary_rpc_method_handler(
            servicer.nextStep,
            request_deserializer=hephaestus__pb2.EnvironmentUpdateContext.FromString,
            response_serializer=hephaestus__pb2.EnvironmentDetail.SerializeToString,
        ),
        'closeEnvironment': grpc.unary_unary_rpc_method_handler(
            servicer.closeEnvironment,
            request_deserializer=hephaestus__pb2.EnvironmentQuery.FromString,
            response_serializer=hephaestus__pb2.EnvironmentDetail.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'RobotSimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


class RobotTaskSimulationServiceStub(object):
    """拣货工作站+机器人模拟服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.createEnvironment = channel.unary_unary(
            '/RobotTaskSimulationService/createEnvironment',
            request_serializer=hephaestus__pb2.TaskEnvironmentCreateContext.SerializeToString,
            response_deserializer=hephaestus__pb2.TaskEnvironmentDetail.FromString,
        )
        self.nextStep = channel.unary_unary(
            '/RobotTaskSimulationService/nextStep',
            request_serializer=hephaestus__pb2.TaskEnvironmentUpdateContext.SerializeToString,
            response_deserializer=hephaestus__pb2.TaskEnvironmentDetail.FromString,
        )
        self.closeEnvironment = channel.unary_unary(
            '/RobotTaskSimulationService/closeEnvironment',
            request_serializer=hephaestus__pb2.EnvironmentQuery.SerializeToString,
            response_deserializer=hephaestus__pb2.TaskEnvironmentDetail.FromString,
        )
        self.calculatePath = channel.unary_unary(
            '/RobotTaskSimulationService/calculatePath',
            request_serializer=hephaestus__pb2.CalculatePathContext.SerializeToString,
            response_deserializer=hephaestus__pb2.CalculatePathResult.FromString,
        )


class RobotTaskSimulationServiceServicer(object):
    """拣货工作站+机器人模拟服务
    """

    def createEnvironment(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def nextStep(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def closeEnvironment(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def calculatePath(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotTaskSimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'createEnvironment': grpc.unary_unary_rpc_method_handler(
            servicer.createEnvironment,
            request_deserializer=hephaestus__pb2.TaskEnvironmentCreateContext.FromString,
            response_serializer=hephaestus__pb2.TaskEnvironmentDetail.SerializeToString,
        ),
        'nextStep': grpc.unary_unary_rpc_method_handler(
            servicer.nextStep,
            request_deserializer=hephaestus__pb2.TaskEnvironmentUpdateContext.FromString,
            response_serializer=hephaestus__pb2.TaskEnvironmentDetail.SerializeToString,
        ),
        'closeEnvironment': grpc.unary_unary_rpc_method_handler(
            servicer.closeEnvironment,
            request_deserializer=hephaestus__pb2.EnvironmentQuery.FromString,
            response_serializer=hephaestus__pb2.TaskEnvironmentDetail.SerializeToString,
        ),
        'calculatePath': grpc.unary_unary_rpc_method_handler(
            servicer.calculatePath,
            request_deserializer=hephaestus__pb2.CalculatePathContext.FromString,
            response_serializer=hephaestus__pb2.CalculatePathResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'RobotTaskSimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


class RobotAlgorithmServiceStub(object):
    """=========================================================================
    中间层gRPC接口定义

    机器人算法服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.execute = channel.unary_unary(
            '/RobotAlgorithmService/execute',
            request_serializer=hephaestus__pb2.RobotEnvironmentContext.SerializeToString,
            response_deserializer=hephaestus__pb2.RobotAlgorithmResult.FromString,
        )


class RobotAlgorithmServiceServicer(object):
    """=========================================================================
    中间层gRPC接口定义

    机器人算法服务
    """

    def execute(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotAlgorithmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'execute': grpc.unary_unary_rpc_method_handler(
            servicer.execute,
            request_deserializer=hephaestus__pb2.RobotEnvironmentContext.FromString,
            response_serializer=hephaestus__pb2.RobotAlgorithmResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'RobotAlgorithmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


class TaskAlgorithmServiceStub(object):
    """机器人任务算法服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.execute = channel.unary_unary(
            '/TaskAlgorithmService/execute',
            request_serializer=hephaestus__pb2.TaskAlgorithmDetail.SerializeToString,
            response_deserializer=hephaestus__pb2.TaskEnvironmentUpdateContext.FromString,
        )


class TaskAlgorithmServiceServicer(object):
    """机器人任务算法服务
    """

    def execute(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskAlgorithmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'execute': grpc.unary_unary_rpc_method_handler(
            servicer.execute,
            request_deserializer=hephaestus__pb2.TaskAlgorithmDetail.FromString,
            response_serializer=hephaestus__pb2.TaskEnvironmentUpdateContext.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'TaskAlgorithmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


class ShelfToManTaskAlgorithmServiceStub(object):
    """货到人赛题算法服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.execute = channel.unary_unary(
            '/ShelfToManTaskAlgorithmService/execute',
            request_serializer=hephaestus__pb2.ShelfToManTaskAlgorithmDetail.SerializeToString,
            response_deserializer=hephaestus__pb2.ShelfToManTasAlgorithmResult.FromString,
        )


class ShelfToManTaskAlgorithmServiceServicer(object):
    """货到人赛题算法服务
    """

    def execute(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShelfToManTaskAlgorithmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'execute': grpc.unary_unary_rpc_method_handler(
            servicer.execute,
            request_deserializer=hephaestus__pb2.ShelfToManTaskAlgorithmDetail.FromString,
            response_serializer=hephaestus__pb2.ShelfToManTasAlgorithmResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'ShelfToManTaskAlgorithmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
